### ISSUE TITLE
Dainoga is giving timeout errors on Sitecore

### ISSUE THREAD

**Issue by PriLookers** [kamsar/Dianoga#107]
Hello,
We have Sitecore v8.2 and  Dianoga v3.1.1.0 set up on our production environment. It was all working fine but we are having critical performance issues with Sitecore CMS, media items are not visible on Content editor and Experience editor and it has slow down CMS.

We've plenty of exceptions from Dianoga and we have posted to Sitecore support as well but they have asked us to get in touch here. 

Please have a look at this error and hopefully you'd be able to point us in some direction.

Thank you,
Priyanka

14712 13:49:25 ERROR Could not run the 'getMediaStream' pipeline for '/sitecore/media library/Logos/Vauxhall'. Original media data will be used.
Exception: System.Threading.ThreadAbortException
Message: Thread was being aborted.
Source: Dianoga
   at Dianoga.MediaOptimizer.Process(MediaStream stream, MediaOptions options)
   at Dianoga.Invokers.GetMediaStreamSync.OptimizeImage.Process(GetMediaStreamPipelineArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.Resources.Media.Media.GetStreamFromPipeline(MediaOptions options, Boolean& canBeCached)

14712 13:49:25 ERROR Application error.
Exception: System.Web.Http

**Comment by Antonytm** [comment]
If you have an issue only with Content editor and Experience editor then you can consider disabling it for `shell` website.
This feature is available starting from 5 version. 

https://github.com/kamsar/Dianoga/blob/master/src/Dianoga/Default%20Config%20Files/Dianoga.DisableForSites.config

**Comment by markgibbons25** [comment]
We have fixed a few performance issues in Dianoga v5.x so I would recommend upgrading. You could also try the v6 for some next-gen image support.
