### ISSUE TITLE
Processing error due to inability to find file

### ISSUE THREAD

**Issue by jeff-varszegi** [kamsar/Dianoga#23]
I've just installed Dianoga  3.1.1, and believe I've followed the instructions correctly. However, when I load up the site, I get many errors like the one below. They seem to indicate that with the default .config files as I'm using them, Dianoga isn't finding the files in the media cache folder to optimize. Have you seen anything like this before? Thanks! - Jeff

27404 22:13:38 ERROR Dianoga: Unable to optimize /Images/Global-US/Customer-Stories/customer/logo due to a processing error! It will be unchanged.
Exception: System.ComponentModel.Win32Exception
Message: The system cannot find the file specified
Source: System
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Dianoga.Optimizers.CommandLineToolOptimizer.ExecuteProcess(String arguments)
   at Dianoga.Optimizers.CommandLineToolOptimizer.ProcessOptimizer(OptimizerArgs args)
   at Dianoga.Optimizers.OptimizerProcessor.Process(OptimizerArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Dianoga.Processors.Pipelines.DianogaOptimize.ExtensionBasedOptimizer.ProcessOptimize(ProcessorArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Dianoga.MediaOptimizer.Process(MediaStream stream, MediaOptions options)

**Comment by eat-sleep-code** [comment]
https://github.com/kamsar/Dianoga/issues/18

**Comment by jeff-varszegi** [comment]
Thanks, I figured it out. Perhaps it'd be good to create a subfolder in a safe place so this would always work out of the box? I'm playing with the module and liking it so far, though not sure how to disable progressive loading on JPEGs which will be necessary if I'm to use this in our production environment.

**Comment by thebernardlim** [comment]
@jeff-varszegi  @kamsar I am also facing this issue currently. What was the change he made to make it work? Thanks.

**Comment by thebernardlim** [comment]
@jeff-varszegi  @kamsar Managed to fix thanks to @kamsar 's help.
Just putting out there for potential users who might face similar issues. These errors happen when the .exe files under 'App_Data\Dianoga Tools' could not be found.
