### ISSUE TITLE
Issue optimizing images

### ISSUE THREAD

**Issue by fmdog** [kamsar/Dianoga#32]
Hi, my sitecore authoring site was running quite slow so I decided to look at the logs and found a number of errors relating to dianoga image optimization. Below is an example

12:45:47 INFO  Dianoga: <image> is not something that can be optimized, either because of its file format or because it is excluded.
12:45:47 ERROR Dianoga: Unable to optimize <image> due to a processing error! It will be unchanged.

Exception: System.IO.IOException
Message: The file exists.

Source: mscorlib
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Dianoga.Optimizers.CommandLineToolOptimizer.GetTempFilePath()
   at Dianoga.Optimizers.CommandLineToolOptimizer.ProcessOptimizer(OptimizerArgs args)
   at Dianoga.Optimizers.OptimizerProcessor.Process(OptimizerArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Dianoga.Processors.Pipelines.DianogaOptimize.ExtensionBasedOptimizer.ProcessOptimize(ProcessorArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Dianoga.MediaOptimizer.Process(MediaStream stream, MediaOptions options)

Do you have any idea what may be causing this issue? I am running Sitecore.NET 8.2 (rev. 160729) and Dianoga  version 3.1.1

Thank you

**Comment by fmdog** [comment]
I should add that I do not have any config settings in place to exclude any images

**Comment by kamsar** [comment]
Normally there would be an item path in that 'is not something that can be optimized'. It looks like there might be some sort of corrupted media item or possibly something requesting the root media url (a guess). 




On Fri, Feb 9, 2018 at 6:20 AM -0800, "fmdog" <notifications@github.com> wrote:












I should add that I do not have any config settings in place to exclude any images

**Comment by kamsar** [comment]
Here is the code that emits that log: https://github.com/kamsar/Dianoga/blob/c0eb1ef07eedf317c04abd5d74d368ee39644cc5/src/Dianoga/Invokers/MediaCacheAsync/OptimizingMediaCache.cs#L87

This in turn implies that `stream.MediaItem.MediaPath` is null or empty which seems to imply to me anyway that there's something quite funny going on with a media item's data.

**Comment by fmdog** [comment]
Sorry, I actually just removed the media path from the comment. The logs do have the image path included.

**Comment by kamsar** [comment]
What kind of media file is it? Is it's extension field correct? Is it a valid readable image?




On Sat, Feb 10, 2018 at 9:22 AM -0800, "fmdog" <notifications@github.com> wrote:












Sorry, I actually just removed the media path from the comment. The logs do have the image path included.

**Comment by fmdog** [comment]
It's a JPEG and everything looks ok in Sitecore. The extension field is "jpg". I have downloaded the image from the media library as well and have no issues viewing it.

**Comment by sebastianlay** [comment]
I had the same error when I had a media item with a whitespace character in the name. Maybe try renaming the media item?
