### ISSUE TITLE
"ERROR Could not add media to cache." when Dianoga is unable to optimize an image due to a processing error 

### ISSUE THREAD

**Issue by mjarosch** [kamsar/Dianoga#34]
Anytime the command line optimizers exit with an error code, we are seeing an exception in SC trying to add it to the cache and get the yellow page of death. For example, if a PNG file is uploaded to the media library with a JPG extension (I know, I have reported it to the content team to fix, but still), attempting to download or view it will error.

3632 09:18:56 ERROR Dianoga: Unable to optimize /path/to/image due to a processing error! It will be unchanged.
Exception: System.InvalidOperationException
Message: E:\path\to\site\Website\App_Data\Dianoga Tools\PNGOptimizer\PNGOptimizerCL.exe exited with unexpected exit code 1. Output: 

 (KO) Unsupported file format

Optimizing tmp3DEC.png 
Source: Dianoga
   at Dianoga.Optimizers.CommandLineToolOptimizer.ExecuteProcess(String arguments)
   at Dianoga.Optimizers.CommandLineToolOptimizer.ProcessOptimizer(OptimizerArgs args)
   at Dianoga.Optimizers.OptimizerProcessor.Process(OptimizerArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Dianoga.Processors.Pipelines.DianogaOptimize.ExtensionBasedOptimizer.ProcessOptimize(ProcessorArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Dianoga.MediaOptimizer.Process(MediaStream stream, MediaOptions options)

3632 09:18:56 ERROR Could not add media to cache. Media item id: {XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
Exception: System.ObjectDisposedException
Message: Cannot access a closed Stream.
Source: mscorlib
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.get_Length()
   at Sitecore.IO.StreamSharer..ctor(Stream masterStream, String bufferFilePath)
   at Sitecore.Resources.Media.MediaCacheRecord.Initialize(Media sitecoreMedia, MediaOptions mediaOptions, MediaStream mediaStream)
   at Sitecore.Resources.Media.MediaCache.CreateCacheRecord(Media media, MediaOptions options, MediaStream stream)
   at Sitecore.Resources.Media.MediaCache.AddStream(Media media, MediaOptions options, MediaStream stream, MediaStream& cachedStream)
   at Sitecore.Resources.Media.Media.AddStreamToCache(MediaOptions options, MediaStream mediaStream, MediaStream& cachedStream)

**Comment by mjarosch** [comment]
We were running 8.2 Update 2 at the time I reported the issue. We have since upgraded to 9.0 Update 1, and haven't had an opportunity to see if it is still happening.

**Comment by josedbaez** [comment]
This is actually happening to us atm. There's one image that "PNGOptimizerCL.exe" can't optimise and we end up with yellow page of death.

> 140096 14:03:20 ERROR Dianoga: Unable to optimize /Project/xxx/Global/Images/xxx-logo due to a processing error! It will be unchanged.
Exception: System.InvalidOperationException
Message: C:\inetpub\wwwroot\xxxxxl\App_Data\Dianoga Tools\PNGOptimizer\PNGOptimizerCL.exe exited with unexpected exit code 1. Output: 
(KO) Unsupported file format
Optimizing tmp478A.png 
Source: Dianoga
  at Dianoga.Optimizers.CommandLineToolOptimizer.ExecuteProcess(String arguments)
   at Dianoga.Optimizers.CommandLineToolOptimizer.ProcessOptimizer(OptimizerArgs args)
   at Dianoga.Optimizers.OptimizerProcessor.Process(OptimizerArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Dianoga.Processors.Pipelines.DianogaOptimize.ExtensionBasedOptimizer.ProcessOptimize(ProcessorArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Dianoga.MediaOptimizer.Process(MediaStream stream, MediaOptions options)
140096 14:03:20 ERROR Could not add media to cache. Media item id: {3785C7B2-29CE-495C-B2DF-5D0D2DA89668}
Exception: System.ObjectDisposedException
Message: Cannot access a closed Stream.
Source: mscorlib
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.get_Length()
   at Sitecore.IO.StreamSharer..ctor(Stream masterStream, String bufferFilePath)
   at Sitecore.Resources.Media.MediaCacheRecord.Initialize(Media sitecoreMedia, MediaOptions mediaOptions, MediaStream mediaStream)
   at Sitecore.Resources.Media.MediaCache.CreateCacheRecord(Media media, MediaOptions options, MediaStream stream)
   at Sitecore.Resources.Media.MediaCache.AddStream(Media media, MediaOptions options, MediaStream stream, MediaStream& cachedStream)
   at Sitecore.Resources.Media.Media.AddStreamToCache(MediaOptions options, MediaStream mediaStream, MediaStream& cachedStream)

**Comment by josedbaez** [comment]
I got the issue @mjarosch mentioned but re-added the latest 4.0 nuget package and error is gone now...

**Comment by mzizka** [comment]
Still have this issue in the latest. In my case, I have an image that nQuant is unable to process. In asynchronous mode, the optimizer fails gracefully and the original image is produced and cached. A message is logged once and is never seen again for that same image.

But in synchronous mode, the image can't load or be cached, and I get the following error sequence each time:

    [14352] 15:28:19 ERROR Dianoga.MediaOptimizer - Dianoga: Unable to optimize /XXX/XX/XXXXX due to a processing error! It will be unchanged.
    Exception: nQuant.QuantizationException
    Message: The image you are attempting to quantize does not contain a 32 bit ARGB palette. This image has a bit depth of 24 with 0 colors.
    Source: nQuant.Core
       ...

    [14352] 15:28:19 ERROR Sitecore.Resources.Media.ImageMedia - Could not add media to cache. Media item id: {XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
    Exception: System.ObjectDisposedException
    Message: Cannot access a closed Stream.
    Source: mscorlib
       ...
       at Sitecore.IO.StreamSharer..ctor(Stream masterStream, String bufferFilePath)
       at Sitecore.Resources.Media.MediaCacheRecord.Initialize(Media sitecoreMedia, MediaOptions mediaOptions, MediaStream mediaStream)
       ...

    [14352] 15:28:19 ERROR Sitecore.Nexus.Web.HttpModule - Application error.
    Exception: System.ObjectDisposedException
    Message: Cannot access a closed Stream.
    Source: mscorlib
       ...
       at Sitecore.Resources.Media.Streaming.RangeRetrievalResponse.WriteFullContent(HttpContext context, Stream fileContent)
       at Sitecore.Resources.Media.MediaRequestHandler.DoProcessRequest(HttpContext context, MediaRequest request, Media media)
       ...

**Comment by bartlomiejmucha** [comment]
@mjarosch why not to disable Dianoga completely on the CM server? It wastes CPU, especially if you use jpegoptim lossy compression. You need to optimize images mostly for SEO on CD servers. 
If you have a standalone instance, check out my https://github.com/kamsar/Dianoga/pull/41 it allows to enable Dianoga per site.

**Comment by markgibbons25** [comment]
Looks like this might be happening due to a race condition https://kb.sitecore.net/articles/843582

**Comment by markgibbons25** [comment]
I did find an issue here, it should be fixed https://github.com/kamsar/Dianoga/releases/tag/5.0.0-beta.1 please retest
