### ISSUE TITLE
Issue optimizing images after Dianoga.3.1.1 installation on sitecore (version Sitecore.NET 8.2)

### ISSUE THREAD

**Issue by hrama22** [kamsar/Dianoga#38]
Hi ,
I installed the Dianoga.3.1.1 NuGet package using visual studio and cleared App_Data\MediaCache.

I browsed some of the  pages in my web site  and checked the logs .It is is throwing below error and not optimizing the  jpg and png images.

9556 06:59:17 INFO  Dianoga:(Item path) is not something that can be optimized, either because of its file format or because it is excluded.
11068 06:59:17 ERROR Dianoga: Unable to optimize (Item Path) due to a processing error! It will be unchanged.
Exception: System.ComponentModel.Win32Exception
Message: The system cannot find the file specified
Source: System
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Dianoga.Optimizers.CommandLineToolOptimizer.ExecuteProcess(String arguments)
   at Dianoga.Optimizers.CommandLineToolOptimizer.ProcessOptimizer(OptimizerArgs args)
   at Dianoga.Optimizers.OptimizerProcessor.Process(OptimizerArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Dianoga.Processors.Pipelines.DianogaOptimize.ExtensionBasedOptimizer.ProcessOptimize(ProcessorArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Dianoga.MediaOptimizer.Process(MediaStream stream, MediaOptions options)

Can you please help me in this?

**Comment by kamsar** [comment]
FYI, in the next version I'm altering it to emit the binary path that it tried to start as well as the inner exception. That should make diagnosing this kind of issue much easier.
