### ISSUE TITLE
ERROR Dianoga: Unable to optimize /TestingTwo due to a processing error! It will be unchanged.

### ISSUE THREAD

**Issue by uday420** [kamsar/Dianoga#63]
Hi 

I'm trying to setup Dianoga on sitecore 9.0.1 through Nuget Package installer. It seems to be working on some images but when i look at the logs i get following error,

```
40196 14:39:00 INFO  "C:\Websites\Project\App_Data\Dianoga Tools\libwebp-1.1.0-windows-x64\bin\cwebp.exe -preset photo "C:\WINDOWS\TEMP\tmp439C.tmp" -o "C:\WINDOWS\TEMP\tmp439D.tmp" "
40196 14:39:00 ERROR Dianoga: Unable to optimize /TestingTwo due to a processing error! It will be unchanged.
Exception: System.InvalidOperationException
Message: "C:\Websites\Project\App_Data\Dianoga Tools\libwebp-1.1.0-windows-x64\bin\cwebp.exe -preset photo "C:\WINDOWS\TEMP\tmp439C.tmp" -o "C:\WINDOWS\TEMP\tmp439D.tmp" " could not be started because an error occurred. See the inner exception for details.
Source: Dianoga
   at Dianoga.Optimizers.CommandLineToolOptimizer.ExecuteProcess(String arguments)
   at Dianoga.Optimizers.CommandLineToolOptimizer.ProcessOptimizer(OptimizerArgs args)
   at Dianoga.Optimizers.OptimizerProcessor.Process(OptimizerArgs args)
   at Dianoga.Optimizers.Pipelines.DianogaWebP.WebPOptimizer.Process(OptimizerArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Dianoga.Processors.Pipelines.DianogaOptimize.ExtensionBasedOptimizer.ProcessOptimize(ProcessorArgs args)
   at Dianoga.Processors.Pipelines.DianogaOptimize.DianogaOptimizeProcessor.Process(ProcessorArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Dianoga.MediaOptimizer.Process(MediaStream stream, MediaOptions options)

Nested Exception

Exception: System.ComponentModel.Win32Exception
Message: The system cannot find the file specified
Source: System
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Dianoga.Optimizers.CommandLineToolOptimizer.ExecuteProcess(String arguments)


40196 14:39:00 INFO  Dianoga: /TestingTwo cannot be optimized due to media type or path exclusion
```

Using Dianoga Version **4.0.0**

Image uploaded in sitecore is an jpg format not sure why it throws error as at run time im expecting to display in webp format, will you able to help me resolve this issue?

Best Regards - Us

**Comment by markgibbons25** [comment]
Hi, please use Dianoga 5 RC 4 if you want webp functionality.

**Comment by uday420** [comment]
Hi @markgibbons25 

Is this  build safer to run in prod environment ?

Thanks -Us

**Comment by markgibbons25** [comment]
Hi @uday420 
If you're not using a CDN then yes it's safer - see the https://github.com/kamsar/Dianoga/releases/tag/5.0.0-rc.4 release notes for all the changes and fixes. I have it running in a prod environment. But note there is an issue with CDN support, but you're safe if you have no CDN.
